### ISSUE TITLE
CursorNotFound exception when processing large stakeholder

### ISSUE THREAD

**Issue by dav3r** [dhs-ncats/trustymail_reporter#39]
# 🐛 Bug Report

During the weekly report generation process, we are getting the following error when processing one of our larger stakeholders (HHS):

```
/var/cyhy/orchestrator# docker-compose logs trustymail_report | less

trustymail_report_1  Generating Trustymail Report...
trustymail_report_1  Traceback (most recent call last):
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 1329, in <module>
trustymail_report_1      main()
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 1319, in main
trustymail_report_1      generator = ReportGenerator(db, args['"AGENCY"'], debug=args['--debug'])
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 218, in __init__
trustymail_report_1      for domain_doc in all_domains_cursor:
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
trustymail_report_1      if len(self.__data) or self._refresh():
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1093, in _refresh
trustymail_report_1      self.__send_message(g)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
trustymail_report_1      address=self.__address)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
trustymail_report_1      exhaust=exhaust)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
trustymail_report_1      return func(session, server, sock_info, slave_ok)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
trustymail_report_1      unpack_res)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
trustymail_report_1      _check_command_response(first)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 156, in _check_command_response
trustymail_report_1      raise CursorNotFound(errmsg, code, response)
trustymail_report_1  pymongo.errors.CursorNotFound: cursor id 228032354899 not found
```

## To Reproduce

I was unable to reproduce this error by generating the individual report manually.  I suspect it can only be triggered by generating all of the reports (`create_all_reports.py`).

## Expected behavior

The report should generate without any errors.

## Potential solutions

Since the MongoDB cursor timeout is occurring [here](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L218) (as seen in the traceback above), we need to look at where `all_domains_cursor` is created [here](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L155-L159).  Two potential solutions are:
- Try using the `batch_size` parameter to work through the cursor results in smaller batches.
- Set `no_cursor_timeout` to `True` and manually close the cursor (`all_domains_cursor.close()`) when processing is finished.

See [the docs](https://api.mongodb.com/python/current/api/pymongo/collection.html) for details.

**Comment by jsf9k** [comment]
I think the cursor is timing out and closing after ten minutes of inactivity, [as described in the docs](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.find).  This is because the query [here](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L162-L200) is taking more than ten minutes to complete.  Fixing this seems as simple as moving [this code](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L155-L160) to just before [this line](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L218).

What do you think @dav3r?

**Comment by dav3r** [comment]
@jsf9k - Yes, that makes sense to me and should fix the problem.  I don't see any issues with that solution.  Nice and simple- I like it. 👍

**Comment by jsf9k** [comment]
I ended up needing to use `no_cursor_timeout` after all.  See #40 for details.
